routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPinjamanController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\PengajuanPinjamanController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\JenisPinjamanController;
use App\Http\Controllers\Admin\PinjamanController;
use App\Http\Controllers\Admin\PembayaranController;
use App\Http\Controllers\UserPengajuanController;
use App\Http\Controllers\UserPembayaranController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PenggunaController;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/profile', [AdminController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [AdminController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [AdminController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [AdminController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [AdminController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', [CustomerController::class, 'index'])->name('index');
            Route::get('/add', [CustomerController::class, 'create'])->name('create');
            Route::post('/add', [CustomerController::class, 'store'])->name('store');
            Route::get('/{user:id}/detail', [CustomerController::class, 'show'])->name('show');
            Route::get('/{user:id}/verif', [CustomerController::class, 'verif'])->name('verif');
            Route::get('/{user:id}', [CustomerController::class, 'edit'])->name('edit');
            Route::get('/{anggota:id}/approved', [CustomerController::class, 'approved'])->name('approved');
            Route::get('/{anggota:id}/reject', [CustomerController::class, 'reject'])->name('reject');
            Route::put('/update/{user:id}', [CustomerController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'pengguna.'], function () {
            Route::get('/', [PenggunaController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PenggunaController::class, 'show'])->name('show');
            Route::post('/update', [PenggunaController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'jenisPinjaman', 'as' => 'jenisPinjaman.'], function () {
            Route::get('/', [JenisPinjamanController::class, 'index'])->name('index');
            Route::get('/add', [JenisPinjamanController::class, 'create'])->name('create');
            Route::post('/add', [JenisPinjamanController::class, 'store'])->name('store');
            Route::get('/{jenis_pinjaman:id}/detail', [JenisPinjamanController::class, 'show'])->name('show');
            Route::get('/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'edit'])->name('edit');
            Route::put('/update/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [PengajuanPinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PengajuanPinjamanController::class, 'show'])->name('show');
            Route::get('/approved/{pengajuan:id}', [PengajuanPinjamanController::class, 'approved'])->name('approved');
            Route::get('/reject/{pengajuan:id}', [PengajuanPinjamanController::class, 'reject'])->name('reject');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [PinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PinjamanController::class, 'show'])->name('show');
            Route::get('/bayar/{id}', [PinjamanController::class, 'bayar'])->name('bayar');
        });

        Route::group(['prefix' => 'laporan', 'as' => 'laporan.'], function () {
            Route::get('/', [LaporanController::class, 'index'])->name('index');
            Route::post('/download', [LaporanController::class, 'download'])->name('download');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [PembayaranController::class, 'index'])->name('index');
            Route::get('/add', [PembayaranController::class, 'add'])->name('add');
            Route::get('/show/{id}', [PembayaranController::class, 'show'])->name('show');
            Route::get('/cetak/{id}', [PembayaranController::class, 'cetak'])->name('cetak');
            Route::post('/bayar', [PembayaranController::class, 'store'])->name('store');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/profile', [UserController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [UserController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [UserController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [UserController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [UserController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'identity', 'as' => 'identity.'], function () {
            Route::get('/upload', [UserController::class, 'uploadIdentity'])->name('upload');
            Route::post('/upload', [UserController::class, 'uploadIdentityStore'])->name('store');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [UserPinjamanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPinjamanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPinjamanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [UserPengajuanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPengajuanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPengajuanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [UserPembayaranController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPembayaranController::class, 'detail'])->name('detail');
        });
    });
});

app/Models/Pengajuan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Pinjaman;
use App\Models\Tagihan;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class Pengajuan extends Model
{
    protected $table = 'pengajuan';
    protected $fillable = [
        'anggota_id',
        'jenis_pinjaman_id',
        'jumlah',
        'tenor',
        'jenis_tenor',
        'jumlah_angsur',
        'angsuran',
        'tanggal_pengajuan',
        'status',
    ];

    public function anggota()
    {
        return $this->hasOne(Anggota::class, 'id', 'anggota_id')->with('user');
    }

    public function jenis()
    {
        return $this->hasOne(JenisPinjaman::class, 'id', 'jenis_pinjaman_id');
    }

    public function initPinjaman()
    {
        DB::beginTransaction();
        try {
            $pinjaman = Pinjaman::query()->where('pengajuan_id', $this->id)->first();
            $jenis = JenisPinjaman::query()->where('id', $this->jenis_pinjaman_id)->first();
            $bunga = $this->jumlah * $jenis->bunga / 100;
            if (!$pinjaman) {
                $pinjaman = new Pinjaman;
                $pinjaman->jenis_pinjaman_id = $this->jenis_pinjaman_id;
                $pinjaman->pengajuan_id = $this->id;
                $pinjaman->invoice = $this->quickRandom();
                $pinjaman->anggota_id = $this->anggota_id;
                $pinjaman->bunga = $bunga;
                $pinjaman->jumlah_pinjaman = $this->jumlah;
                $pinjaman->biaya_layanan = $this->jenis->biaya_layanan;
                $pinjaman->jumlah_diterima = $this->jumlah - $this->jenis->biaya_layanan;
                $pinjaman->flag_lunas = false;
                $pinjaman->save();
            }
            $angsuran_bunga = $bunga / $this->jumlah_angsur;

            $now = Carbon::now();
            $newDateTime = Carbon::now()->addDay();
            $x = 0;
            for ($i = 0; $i < $this->jumlah_angsur; $i++) {
                // jika jenis tenor = hari
                if ($this->jenis_tenor == 'hari') {
                    $interval = round($this->tenor / $this->jumlah_angsur);
                }

                // jika jenis tenor = minggu
                if ($this->jenis_tenor == 'minggu') {
                    $jumlah_hari = $this->tenor * 7;
                    $interval = round($jumlah_hari / $this->jumlah_angsur);
                }

                // jika jenis tenor = bulan
                if ($this->jenis_tenor == 'bulan') {
                    $jumlah_hari = $this->tenor * 30;
                    $interval = round($jumlah_hari / $this->jumlah_angsur);
                }

                $x += $interval;
                $date = $now->addDay($x)->format('Y-m-d');
                $tagihan = new Tagihan;
                $tagihan->pinjaman_id = $pinjaman->id;
                $tagihan->angsuran = $this->angsuran;
                $tagihan->angsuran_ke = $i + 1;
                $tagihan->jatuh_tempo = $date;
                $tagihan->lunas = false;
                $tagihan->bunga = $angsuran_bunga;
                $tagihan->pokok = $this->angsuran - $angsuran_bunga;
                $tagihan->save();
            }

            DB::commit();
        } catch (\Throwable $th) {
            DB::rollBack();
            throw $th;
        }
    }

    public static function quickRandom($length = 12)
    {
        $pool = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';

        return substr(str_shuffle(str_repeat($pool, 5)), 0, $length);
    }
}

resources/views/admin/pengajuan/add.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h6>Tambah Jenis Pinjaman</h6>
                    <a href="{{route('admin.jenisPinjaman.index')}}" class="btn btn-dark btn-sm"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{route('admin.jenisPinjaman.store')}}" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-6">
                                @csrf
                                <div class="form-group">
                                    <label for="jenis_pinjaman">Jenis Pinjaman</label>
                                    <input type="text" name="jenis_pinjaman" class="form-control @error('jenis_pinjaman') is-invalid @enderror" placeholder="Jenis Pinjaman" value="{{old('jenis_pinjaman')}}">
                                    @error('jenis_pinjaman')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="jumlah">Limit Pinjaman</label>
                                    <input type="number" name="jumlah" class="form-control @error('jumlah') is-invalid @enderror" placeholder="Limit Pinjaman" value="{{old('jumlah')}}">
                                    @error('jumlah')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>



                                <div class="form-group">
                                    <label for="tenor">Tenor</label>
                                    <input type="number" name="tenor" class="form-control @error('tenor') is-invalid @enderror" placeholder="Tenor" value="{{old('tenor')}}">
                                    @error('tenor')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="jenis_tenor">Jenis Tenor</label>
                                    <select name="jenis_tenor" id="jenis_tenor" class="form-control @error('jenis_tenor') is-invalid @enderror">
                                        <option value="">Pilih Jenis Tenor</option>
                                        <option value="hari" >Hari</option>
                                        <option value="minggu" >Minggu</option>
                                        <option value="bulan" >Bulan</option>
                                    </select>
                                    @error('jenis_tenor')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>



                            </div>

                            <div class="col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label for="jumlah_angsur">Jumlah Angsur</label>
                                    <input type="number" name="jumlah_angsur" class="form-control @error('jumlah_angsur') is-invalid @enderror" placeholder="Jumlah Angsur" value="{{old('jumlah_angsur')}}">
                                    @error('jumlah_angsur')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="biaya_layanan">Biaya Layanan</label>
                                    <input type="number" name="biaya_layanan" class="form-control @error('biaya_layanan') is-invalid @enderror" placeholder="Biaya Layanan" value="{{old('biaya_layanan')}}">
                                    @error('biaya_layanan')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="denda">Denda Keterlambatan  (%)</label>
                                    <input type="number" name="denda" class="form-control @error('denda') is-invalid @enderror" placeholder="Denda Keterlambatan" value="{{old('denda')}}">
                                    @error('denda')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="score_minimum">Skor Minimum</label>
                                    <input type="number" name="score_minimum" class="form-control @error('score_minimum') is-invalid @enderror" placeholder="Skor Minimum" value="{{old('score_minimum')}}">
                                    @error('score_minimum')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection

resources/views/admin/pengajuan/edit.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h6>Tambah Jenis Pinjaman</h6>
                    {{-- <a href="{{route('users.jenisPinjaman.index')}}" class="btn btn-dark btn-sm"><i class="fa fa-arrow-left"></i> Kembali</a> --}}
                    <a href="{{route('admin.jenisPinjaman.index')}}" class="btn btn-dark btn-sm"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <div class="card-body">
                   <form method="POST" action="{{route('admin.jenisPinjaman.update', $data->id)}}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-6">
                                @csrf
                                <div class="form-group">
                                    <label for="jenis_pinjaman">Jenis Pinjaman</label>
                                    <input type="text" name="jenis_pinjaman" class="form-control @error('jenis_pinjaman') is-invalid @enderror" placeholder="Jenis Pinjaman" value="{{old('jenis_pinjaman', $data->jenis_pinjaman)}}">
                                    @error('jenis_pinjaman')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="jumlah">Limit Pinjaman</label>
                                    <input type="number" name="jumlah" class="form-control @error('jumlah') is-invalid @enderror" placeholder="Limit Pinjaman" value="{{old('jumlah', $data->jumlah)}}">
                                    @error('jumlah')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>



                                <div class="form-group">
                                    <label for="tenor">Tenor</label>
                                    <input type="number" name="tenor" class="form-control @error('tenor') is-invalid @enderror" placeholder="Tenor" value="{{old('tenor', $data->jumlah)}}">
                                    @error('tenor')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="jenis_tenor">Jenis Tenor</label>
                                    <select name="jenis_tenor" id="jenis_tenor" class="form-control @error('jenis_tenor') is-invalid @enderror">
                                        <option value="">Pilih Jenis Tenor</option>
                                        <option value="hari" {{$data->jenis_tenor == 'hari' ? 'selected' : ''}}>Hari</option>
                                        <option value="minggu" {{$data->jenis_tenor == 'minggu' ? 'selected' : ''}}>Minggu</option>
                                        <option value="bulan" {{$data->jenis_tenor == 'bulan' ? 'selected' : ''}}>Bulan</option>
                                    </select>
                                    @error('jenis_tenor')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>



                            </div>

                            <div class="col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group">
                                    <label for="jumlah_angsur">Jumlah Angsur</label>
                                    <input type="number" name="jumlah_angsur" class="form-control @error('jumlah_angsur') is-invalid @enderror" placeholder="Jumlah Angsur" value="{{old('jumlah_angsur', $data->jumlah_angsur)}}">
                                    @error('jumlah_angsur')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="biaya_layanan">Biaya Layanan</label>
                                    <input type="number" name="biaya_layanan" class="form-control @error('biaya_layanan') is-invalid @enderror" placeholder="Biaya Layanan" value="{{old('biaya_layanan', $data->biaya_layanan)}}">
                                    @error('biaya_layanan')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="denda">Denda Keterlambatan (%)</label>
                                    <input type="number" name="denda" class="form-control @error('denda') is-invalid @enderror" placeholder="Denda Keterlambatan" value="{{old('denda', $data->denda)}}">
                                    @error('denda')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="score_minimum">Skor Minimum</label>
                                    <input type="number" name="score_minimum" class="form-control @error('score_minimum') is-invalid @enderror" placeholder="Skor Minimum" value="{{old('score_minimum', $data->score_minimum)}}">
                                    @error('score_minimum')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection

resources/views/admin/pengajuan/show.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div>
        <a href="{{route('admin.pengajuan.index')}}" class="btn btn-link"><i class="fa fa-arrow-left"></i> Kembali</a>
    </div>
    <div class="row">
        <div class="col-12 col-xl-4">
            <div class="card h-100">
                <div class="card-header pb-0 p-3">
                    <div class="row">
                        <div class="col-md-8 d-flex align-items-center">
                            <h6 class="mb-0">Informasi Pengajuan</h6>
                        </div>
                    </div>
                </div>
                <div class="card-body p-3">
                    <hr class="horizontal gray-light my-4">
                    <ul class="list-group">
                        <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Produk:</strong> &nbsp; {{$pengajuan->jenis->jenis_pinjaman}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Jumlah Pengajuan:</strong> &nbsp;{{"Rp. ".number_format($pengajuan->jumlah)}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Biaya Layanan:</strong> &nbsp; {{"Rp. ".number_format($pengajuan->jenis->biaya_layanan)}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Jumlah Diterima:</strong> &nbsp; {{"Rp. ".number_format($pengajuan->jumlah - $pengajuan->jenis->biaya_layanan)}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Tenor:</strong> &nbsp; {{$pengajuan->tenor." ".$pengajuan->jenis_tenor}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Jumlah Angsuran:</strong> &nbsp; {{$pengajuan->jumlah_angsuran}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Nilai Angsuran:</strong> &nbsp; {{"Rp. ".number_format($pengajuan->angsuran)}}</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-12 col-xl-4">
            <div class="card h-100">
                <div class="card-header pb-0 p-3">
                    <div class="row">
                        <div class="col-md-8 d-flex align-items-center">
                            <h6 class="mb-0">Informasi Anggota</h6>
                        </div>
                    </div>
                </div>
                <div class="card-body p-3">
                    <hr class="horizontal gray-light my-4">
                    <ul class="list-group">
                        <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Nama:</strong> &nbsp; {{$pengajuan->anggota->user->name}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Email:</strong> &nbsp;{{$pengajuan->anggota->user->email}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Alamat:</strong> &nbsp; {{$pengajuan->anggota->user->address}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Jenis Kelamin:</strong> &nbsp; {{$pengajuan->anggota->user->gender}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Phone:</strong> &nbsp; {{$pengajuan->anggota->user->phone}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Pekerjaan:</strong> &nbsp; {{$pengajuan->anggota->pekerjaan}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Skor Kredit:</strong> &nbsp; {{$pengajuan->anggota->skore}}</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-12 col-xl-4">
            <div class="card card-blog card-plain h-100">
                <div class="position-relative">

                    @if($pengajuan->anggota->file_ktp)
                    <a class="d-block shadow-xl border-radius-xl">
                        <img src="{{asset('assets/img/ktp/'.$pengajuan->anggota->file_ktp)}}" alt="img-blur-shadow" class="img-fluid shadow border-radius-xl">
                    </a>
                    @else
                    <a class="d-block shadow-xl border-radius-xl">
                        <img src="{{asset('assets/img/curved-images/white-curved.jpg')}}" alt="img-blur-shadow" class="img-fluid shadow border-radius-xl">
                    </a>
                    @endif
                </div>
                <div class="card-body px-1 pb-0">
                    <p class="text-gradient text-dark mb-2 text-sm">KTP FILE</p>
                    <p class="text-gradient text-dark mb-2 text-sm">Nomor KTP</p>
                    <a href="javascript:;">
                        <h5>
                            {{$pengajuan->anggota->nomor_ktp}}
                        </h5>
                    </a>

                </div>
                @if($pengajuan->status=='menunggu persetujuan')
                <a href="{{route('admin.pengajuan.approved', $pengajuan->id)}}" class="btn btn-success btn-sm px-2 py-2 text-xs">
                    Setujui
                </a>
                <a href="{{route('admin.pengajuan.reject', $pengajuan->id)}}" class="btn btn-danger btn-sm px-2 py-2 text-xs">
                    Tolak
                </a>

                @endif
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection