routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPinjamanController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\PengajuanPinjamanController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\JenisPinjamanController;
use App\Http\Controllers\Admin\PinjamanController;
use App\Http\Controllers\Admin\PembayaranController;
use App\Http\Controllers\UserPengajuanController;
use App\Http\Controllers\UserPembayaranController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PenggunaController;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/profile', [AdminController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [AdminController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [AdminController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [AdminController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [AdminController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', [CustomerController::class, 'index'])->name('index');
            Route::get('/add', [CustomerController::class, 'create'])->name('create');
            Route::post('/add', [CustomerController::class, 'store'])->name('store');
            Route::get('/{user:id}/detail', [CustomerController::class, 'show'])->name('show');
            Route::get('/{user:id}/verif', [CustomerController::class, 'verif'])->name('verif');
            Route::get('/{user:id}', [CustomerController::class, 'edit'])->name('edit');
            Route::get('/{anggota:id}/approved', [CustomerController::class, 'approved'])->name('approved');
            Route::get('/{anggota:id}/reject', [CustomerController::class, 'reject'])->name('reject');
            Route::put('/update/{user:id}', [CustomerController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'pengguna.'], function () {
            Route::get('/', [PenggunaController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PenggunaController::class, 'show'])->name('show');
            Route::post('/update', [PenggunaController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'jenisPinjaman', 'as' => 'jenisPinjaman.'], function () {
            Route::get('/', [JenisPinjamanController::class, 'index'])->name('index');
            Route::get('/add', [JenisPinjamanController::class, 'create'])->name('create');
            Route::post('/add', [JenisPinjamanController::class, 'store'])->name('store');
            Route::get('/{jenis_pinjaman:id}/detail', [JenisPinjamanController::class, 'show'])->name('show');
            Route::get('/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'edit'])->name('edit');
            Route::put('/update/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [PengajuanPinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PengajuanPinjamanController::class, 'show'])->name('show');
            Route::get('/approved/{pengajuan:id}', [PengajuanPinjamanController::class, 'approved'])->name('approved');
            Route::get('/reject/{pengajuan:id}', [PengajuanPinjamanController::class, 'reject'])->name('reject');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [PinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PinjamanController::class, 'show'])->name('show');
            Route::get('/bayar/{id}', [PinjamanController::class, 'bayar'])->name('bayar');
        });

        Route::group(['prefix' => 'laporan', 'as' => 'laporan.'], function () {
            Route::get('/', [LaporanController::class, 'index'])->name('index');
            Route::post('/download', [LaporanController::class, 'download'])->name('download');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [PembayaranController::class, 'index'])->name('index');
            Route::get('/add', [PembayaranController::class, 'add'])->name('add');
            Route::get('/show/{id}', [PembayaranController::class, 'show'])->name('show');
            Route::get('/cetak/{id}', [PembayaranController::class, 'cetak'])->name('cetak');
            Route::post('/bayar', [PembayaranController::class, 'store'])->name('store');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/profile', [UserController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [UserController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [UserController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [UserController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [UserController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'identity', 'as' => 'identity.'], function () {
            Route::get('/upload', [UserController::class, 'uploadIdentity'])->name('upload');
            Route::post('/upload', [UserController::class, 'uploadIdentityStore'])->name('store');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [UserPinjamanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPinjamanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPinjamanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [UserPengajuanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPengajuanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPengajuanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [UserPembayaranController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPembayaranController::class, 'detail'])->name('detail');
        });
    });
});

app/Models/Pengajuan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Pinjaman;
use App\Models\Tagihan;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class Pengajuan extends Model
{
    protected $table = 'pengajuan';
    protected $fillable = [
        'anggota_id',
        'jenis_pinjaman_id',
        'jumlah',
        'tenor',
        'jenis_tenor',
        'jumlah_angsur',
        'angsuran',
        'tanggal_pengajuan',
        'status',
    ];

    public function anggota()
    {
        return $this->hasOne(Anggota::class, 'id', 'anggota_id')->with('user');
    }

    public function jenis()
    {
        return $this->hasOne(JenisPinjaman::class, 'id', 'jenis_pinjaman_id');
    }

    public function initPinjaman()
    {
        DB::beginTransaction();
        try {
            $pinjaman = Pinjaman::query()->where('pengajuan_id', $this->id)->first();
            $jenis = JenisPinjaman::query()->where('id', $this->jenis_pinjaman_id)->first();
            $bunga = $this->jumlah * $jenis->bunga / 100;
            if (!$pinjaman) {
                $pinjaman = new Pinjaman;
                $pinjaman->jenis_pinjaman_id = $this->jenis_pinjaman_id;
                $pinjaman->pengajuan_id = $this->id;
                $pinjaman->invoice = $this->quickRandom();
                $pinjaman->anggota_id = $this->anggota_id;
                $pinjaman->bunga = $bunga;
                $pinjaman->jumlah_pinjaman = $this->jumlah;
                $pinjaman->biaya_layanan = $this->jenis->biaya_layanan;
                $pinjaman->jumlah_diterima = $this->jumlah - $this->jenis->biaya_layanan;
                $pinjaman->flag_lunas = false;
                $pinjaman->save();
            }
            $angsuran_bunga = $bunga / $this->jumlah_angsur;

            $now = Carbon::now();
            $newDateTime = Carbon::now()->addDay();
            $x = 0;
            for ($i = 0; $i < $this->jumlah_angsur; $i++) {
                // jika jenis tenor = hari
                if ($this->jenis_tenor == 'hari') {
                    $interval = round($this->tenor / $this->jumlah_angsur);
                }

                // jika jenis tenor = minggu
                if ($this->jenis_tenor == 'minggu') {
                    $jumlah_hari = $this->tenor * 7;
                    $interval = round($jumlah_hari / $this->jumlah_angsur);
                }

                // jika jenis tenor = bulan
                if ($this->jenis_tenor == 'bulan') {
                    $jumlah_hari = $this->tenor * 30;
                    $interval = round($jumlah_hari / $this->jumlah_angsur);
                }

                $x += $interval;
                $date = $now->addDay($x)->format('Y-m-d');
                $tagihan = new Tagihan;
                $tagihan->pinjaman_id = $pinjaman->id;
                $tagihan->angsuran = $this->angsuran;
                $tagihan->angsuran_ke = $i + 1;
                $tagihan->jatuh_tempo = $date;
                $tagihan->lunas = false;
                $tagihan->bunga = $angsuran_bunga;
                $tagihan->pokok = $this->angsuran - $angsuran_bunga;
                $tagihan->save();
            }

            DB::commit();
        } catch (\Throwable $th) {
            DB::rollBack();
            throw $th;
        }
    }

    public static function quickRandom($length = 12)
    {
        $pool = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';

        return substr(str_shuffle(str_repeat($pool, 5)), 0, $length);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'gender',
        'avatar',
        'dob',
        'address'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function identity()
    {
        return $this->hasOne(UserIdentity::class);
    }

    public function anggota()
    {
        return $this->hasOne(Anggota::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;
use App\Models\Anggota;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function myProfile()
    {
        /** @var User $user*/
        $user = auth()->user();
        $anggota = Anggota::where('user_id', $user->id)->first();
        return view('admin.users.profile', ['user' => $user, 'anggota' => $anggota]);
    }

    public function editProfile()
    {
        $user = User::query()->where('id', Auth::user()->id)->with('anggota')->first();
        return view('admin.users.edit-profile', ['user' => $user]);
    }

    public function update(Request $request)
    {
        /** @var User $user*/
        $user = auth()->user();

        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'phone' => 'required',
            'address' => 'required',
            'gender' => 'required',
            'dob' => 'sometimes|date|nullable',
            'avatar' => 'sometimes|file|mimes:jpg,jpeg,png,gif|max:1024|nullable',
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->phone = $request->phone;
        $user->address = $request->address;
        $user->gender = $request->gender;
        if ($request->has('dob')) {
            $user->dob = $request->dob;
        }

        if ($request->has('pekerjaan')) {
            $anggota = Anggota::query()->where('user_id', $user->id)->first();
            if (!$anggota) {
                $anggota = new Anggota();
                $anggota->nomor_anggota = '-';
                $anggota->user_id = $user->id;
                $anggota->pekerjaan = $request->pekerjaan;
                $anggota->save();
            } else {
                $anggota->pekerjaan = $request->pekerjaan;
                $anggota->update();
            }
        }

        $fileName = null;
        if ($request->hasFile('avatar')) {
            $original_filename      = $request->file('avatar')->getClientOriginalName();
            $original_filename_arr  = explode('.', $original_filename);
            $file_ext               = end($original_filename_arr);
            $destination_path       = public_path('assets/img/avatar');
            $image                  = (string) Str::uuid() . '.' . $file_ext;
            if ($request->file('avatar')->move($destination_path, $image)) {
                $fileName = $image;
            }
            $user->avatar = $fileName;
        }

        $user->save();

        return redirect(route('users.myProfile'))->with(['success' => 'Profil berhasil diubah']);
    }

    public function changePassword()
    {
        return view('admin.users.change-password');
    }

    public function updatePassword(Request $request)
    {
        $request->validate([
            'old_password' => 'required',
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        /** @var User $user*/
        $user = auth()->user();

        $currentPassword = $user->password;
        $oldPassword = $request->old_password;

        if (Hash::check($oldPassword, $currentPassword)) {
            $user->update([
                'password' => Hash::make($request->password),
            ]);
            return back()->with('success', 'Password berhasil diubah');
        } else {
            return back()->with('error', 'Password lama tidak benar');
        }
    }

    public function uploadIdentity()
    {
        return view('admin.users.identity.upload-ktp');
    }

    public function uploadIdentityStore(Request $request)
    {
        $request->validate([
            'ktp_number' => 'required|digits:16|string',
            'ktp_file' => 'required|file|mimes:jpg,png,jpg|max:1024'
        ]);

        /** @var User $user*/

        $user = auth()->user();

        $fileName = null;
        if ($request->hasFile('ktp_file')) {
            $original_filename      = $request->file('ktp_file')->getClientOriginalName();
            $original_filename_arr  = explode('.', $original_filename);
            $file_ext               = end($original_filename_arr);
            $destination_path       = public_path('assets/img/ktp');
            $image                  = (string) Str::uuid() . '.' . $file_ext;
            if ($request->file('ktp_file')->move($destination_path, $image)) {
                $fileName = $image;
            }
        }

        $params = [
            'nomor_ktp' => $request->ktp_number,
            'file_ktp' => $fileName,
        ];

        $check = Anggota::where('user_id', $user->id)->exists();
        if ($check) {
            Anggota::updateOrCreate(['user_id' => $user->id], $params);
        } else {
            $user->anggota()->create($params);
        }

        return redirect(route('users.myProfile'))->with(['success' => 'Ktp berhasil di upload']);
    }
}

resources/views/user/pengajuan/change-password.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h6>Ubah Password</h6>
                    <a href="{{route('users.myProfile')}}" class="btn btn-dark btn-sm"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-4 col-lg-4"></div>
                        <div class="col-sm-12 col-md-8 col-lg-8">
                            <form method="POST" action="{{route('users.change.password')}}">
                                @csrf
                                <div class="form-group">
                                    <label for="old_password">Password Lama</label>
                                    <input type="password" name="old_password" class="form-control @error('old_password') is-invalid @enderror" placeholder="Masukkan password lama">
                                    @error('old_password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password">Password Baru</label>
                                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password baru">
                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password_confirmation">Konfirmasi Password</label>
                                    <input type="password" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror" placeholder="Konfirmasi Password">
                                    @error('password_confirmation')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection

resources/views/user/pengajuan/index.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h6>Daftar Pinjaman</h6>
                    <form method="GET" action="{{route('users.pinjaman.index')}}" enctype="multipart/form-data">
                        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                            <div class="input-group">
                                <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
                                <input type="text" name="search" id="search" class="form-control" placeholder="Type here...">
                            </div>
                        </div>
                    </form>

                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive">
                        <table class="table align-items-center">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-dark text-sm font-weight-bolder opacity-7">#</th>
                                    <th class="text-uppercase text-dark text-sm font-weight-bolder opacity-7 ps-2">Tanggal</th>
                                    <th class="text-uppercase text-dark text-sm font-weight-bolder opacity-7 ps-2">Nama</th>
                                    <th class="text-uppercase text-dark text-sm font-weight-bolder opacity-7 ps-2">Jumlah Pinjaman</th>
                                    <th class="text-uppercase text-dark text-sm font-weight-bolder opacity-7 ps-2">Biaya Layanan</th>
                                    <th class="text-uppercase text-dark text-sm font-weight-bolder opacity-7 ps-2">Status</th>
                                    <th class="text-center text-uppercase text-dark text-sm font-weight-bolder opacity-7">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach($data as $row)
                                <tr>
                                    <td class="align-middle text-center text-sm">
                                        <span class="badge badge-sm bg-gradient-success">{{$loop->iteration}}</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-sm text-dark">{{date('Y-m-d', strtotime($row->created_at))}}</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-sm text-dark">{{$row->anggota->user->name}}</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-dark text-sm">{{"Rp. " .number_format($row->jumlah)}}</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-dark text-sm">{{"Rp. " .number_format($row->jenis->biaya_layanan)}}</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        @if($row->flag_lunas=='1')
                                        <span class="text-dark text-sm">LUNAS</span>
                                        @else
                                        <span class="text-dark text-sm">BELUM LUNAS</span>
                                        @endif

                                    </td>

                                    <td class="align-middle text-center">
                                        <div class="d-flex justify-content-center align-items-center gap-1">
                                            <a href="{{route('users.pengajuan.detail', $row->id)}}" class="btn btn-info btn-sm px-2 py-2 text-xs">
                                                Detail
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>

                        {!! $data->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>

@endsection

resources/views/user/pengajuan/pengajuan.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">

        <div class="col-md-7 mt-4">
            <div class="card">
                <div class="card-header pb-0 px-3">
                    <h6 class="mb-0">Data Pengajuan Pinjaman Anda</h6>
                </div>
                <div class="card-body pt-4 p-3">
                    <ul class="list-group">
                        @foreach($data as $row)
                        <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                            <div class="d-flex flex-column">
                                <h6 class="mb-3 text-sm">{{$row->jenis_pinjaman}}</h6>
                                <span class="mb-2 text-xs">Jumlah Pinjaman: <span class="text-dark font-weight-bold ms-sm-2">{{"Rp." .number_format($row->jumlah)}}</span></span>
                                <span class="text-xs">Tanggal Pengajuan: <span class="text-dark ms-sm-2 font-weight-bold">{{$row->tanggal_pengajuan}}</span></span>
                                <span class="mb-2 text-xs">Jangka Waktu: <span class="text-dark ms-sm-2 font-weight-bold">{{$row->tenor}} - {{$row->jenis_tenor}}</span></span>
                                <span class="text-xs">Jumlah Angsur: <span class="text-dark ms-sm-2 font-weight-bold">{{$row->jumlah_angsur}} kali</span></span>
                                <span class="text-xs">Angsuran: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->angsuran)}}</span></span>
                                <span class="text-xs">Biaya Layanan: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->jenis->biaya_layanan)}}</span></span>
                                <span class="text-xs">Jumlah Diterima: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->jumlah - $row->jenis->biaya_layanan)}}</span></span>

                            </div>

                            <div class="ms-auto text-end">
                                @if($row->status=='menunggu persetujuan')
                                <button class="btn btn-info btn-sm px-2 py-2 text-xs">Menunggu Persetujuan</button>
                                @elseif($row->status=='disetujui')
                                <a href="{{route('users.pinjaman.detail',$row->id)}}" class="btn btn-success btn-sm px-2 py-2 text-xs">Di Setujui</a>
                                @elseif($row->status=='ditolak')
                                <button class="btn btn-danger btn-sm px-2 py-2 text-xs">Ditolak</button>
                                @endif
                            </div>


                        </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>

    </div>

    @include('templates.footer')
</div>
@endsection

resources/views/user/pengajuan/produk-pinjaman.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">

        <div class="col-md-7 mt-4">
            <div class="card">
                <div class="card-header pb-0 px-3">

                    @if($jenisPinjaman != null)
                    <h6 class="mb-0">Produk Untuk Anda</h6>
                    @else
                    <h6 class="mb-0">Mohon maaf, akun anda belum aktif untuk melakukan pengajuan pinjaman, silahkan hubungi petugas kami.</h6>
                    @endif

                </div>
                <div class="card-body pt-4 p-3">
                    <ul class="list-group">
                        @if($jenisPinjaman != null)
                        @foreach($jenisPinjaman as $row)
                        <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                            <div class="d-flex flex-column">
                                <h6 class="mb-3 text-sm">{{$row->jenis_pinjaman}}</h6>
                                <span class="mb-2 text-xs">Jumlah Pinjaman: <span class="text-dark font-weight-bold ms-sm-2">{{"Rp." .number_format($row->jumlah)}}</span></span>
                                <span class="mb-2 text-xs">Jangka Waktu: <span class="text-dark ms-sm-2 font-weight-bold">{{$row->tenor}} - {{$row->jenis_tenor}}</span></span>
                                <span class="text-xs">Jumlah Angsur: <span class="text-dark ms-sm-2 font-weight-bold">{{$row->jumlah_angsur}} kali</span></span>
                                <span class="text-xs">Angsuran: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->angsuran)}} </span></span>
                                <span class="text-xs">Biaya Layanan: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->biaya_layanan)}} </span></span>
                                <span class="text-xs">Bunga: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->jumlah * $row->bunga / 100)}} ({{number_format($row->bunga)}} %) </span></span>
                                <span class="text-xs">Jumlah Diterima: <span class="text-dark ms-sm-2 font-weight-bold">{{"Rp. ".number_format($row->jumlah - $row->biaya_layanan)}} </span></span>
                            </div>
                            <div class="ms-auto text-end">
                                <a href="{{route('users.pinjaman.ajukan', $row->id)}}" class="btn btn-info btn-sm px-2 py-2 text-xs">Ajukan</a>
                            </div>
                        </li>
                        @endforeach
                        @endif
                    </ul>
                </div>
            </div>
        </div>

    </div>

    @include('templates.footer')
</div>
@endsection