routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPinjamanController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\PengajuanPinjamanController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\JenisPinjamanController;
use App\Http\Controllers\Admin\PinjamanController;
use App\Http\Controllers\Admin\PembayaranController;
use App\Http\Controllers\UserPengajuanController;
use App\Http\Controllers\UserPembayaranController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PenggunaController;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/profile', [AdminController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [AdminController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [AdminController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [AdminController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [AdminController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', [CustomerController::class, 'index'])->name('index');
            Route::get('/add', [CustomerController::class, 'create'])->name('create');
            Route::post('/add', [CustomerController::class, 'store'])->name('store');
            Route::get('/{user:id}/detail', [CustomerController::class, 'show'])->name('show');
            Route::get('/{user:id}/verif', [CustomerController::class, 'verif'])->name('verif');
            Route::get('/{user:id}', [CustomerController::class, 'edit'])->name('edit');
            Route::get('/{anggota:id}/approved', [CustomerController::class, 'approved'])->name('approved');
            Route::get('/{anggota:id}/reject', [CustomerController::class, 'reject'])->name('reject');
            Route::put('/update/{user:id}', [CustomerController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'pengguna.'], function () {
            Route::get('/', [PenggunaController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PenggunaController::class, 'show'])->name('show');
            Route::post('/update', [PenggunaController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'jenisPinjaman', 'as' => 'jenisPinjaman.'], function () {
            Route::get('/', [JenisPinjamanController::class, 'index'])->name('index');
            Route::get('/add', [JenisPinjamanController::class, 'create'])->name('create');
            Route::post('/add', [JenisPinjamanController::class, 'store'])->name('store');
            Route::get('/{jenis_pinjaman:id}/detail', [JenisPinjamanController::class, 'show'])->name('show');
            Route::get('/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'edit'])->name('edit');
            Route::put('/update/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [PengajuanPinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PengajuanPinjamanController::class, 'show'])->name('show');
            Route::get('/approved/{pengajuan:id}', [PengajuanPinjamanController::class, 'approved'])->name('approved');
            Route::get('/reject/{pengajuan:id}', [PengajuanPinjamanController::class, 'reject'])->name('reject');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [PinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PinjamanController::class, 'show'])->name('show');
            Route::get('/bayar/{id}', [PinjamanController::class, 'bayar'])->name('bayar');
        });

        Route::group(['prefix' => 'laporan', 'as' => 'laporan.'], function () {
            Route::get('/', [LaporanController::class, 'index'])->name('index');
            Route::post('/download', [LaporanController::class, 'download'])->name('download');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [PembayaranController::class, 'index'])->name('index');
            Route::get('/add', [PembayaranController::class, 'add'])->name('add');
            Route::get('/show/{id}', [PembayaranController::class, 'show'])->name('show');
            Route::get('/cetak/{id}', [PembayaranController::class, 'cetak'])->name('cetak');
            Route::post('/bayar', [PembayaranController::class, 'store'])->name('store');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/profile', [UserController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [UserController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [UserController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [UserController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [UserController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'identity', 'as' => 'identity.'], function () {
            Route::get('/upload', [UserController::class, 'uploadIdentity'])->name('upload');
            Route::post('/upload', [UserController::class, 'uploadIdentityStore'])->name('store');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [UserPinjamanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPinjamanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPinjamanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [UserPengajuanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPengajuanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPengajuanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [UserPembayaranController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPembayaranController::class, 'detail'])->name('detail');
        });
    });
});

resources/views/admin/change-password.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h6>Ubah Password</h6>
                    <a href="{{route('admin.myProfile')}}" class="btn btn-dark btn-sm"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-4 col-lg-4"></div>
                        <div class="col-sm-12 col-md-8 col-lg-8">
                            <form method="POST" action="{{route('admin.change.password')}}">
                                @csrf
                                <div class="form-group">
                                    <label for="old_password">Password Lama</label>
                                    <input type="password" name="old_password" class="form-control @error('old_password') is-invalid @enderror" placeholder="Masukkan password lama">
                                    @error('old_password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password">Password Baru</label>
                                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password baru">
                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="password_confirmation">Konfirmasi Password</label>
                                    <input type="password" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror" placeholder="Konfirmasi Password">
                                    @error('password_confirmation')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
            <div class="card">
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-8">
                            <div class="numbers">
                                <p class="text-sm mb-0 text-capitalize font-weight-bold">Total Pinjaman</p>
                                <h5 class="font-weight-bolder mb-0">
                                    {{"Rp. " .number_format($data['pinjaman'])}}

                                </h5>
                            </div>
                        </div>
                        <div class="col-4 text-end">
                            <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                                <i class="ni ni-money-coins text-lg opacity-10" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
            <div class="card">
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-8">
                            <div class="numbers">
                                <p class="text-sm mb-0 text-capitalize font-weight-bold">Pinjaman Terbayar</p>
                                <h5 class="font-weight-bolder mb-0">
                                    {{"Rp. " .number_format($data['pembayaran'])}}

                                </h5>
                            </div>
                        </div>
                        <div class="col-4 text-end">
                            <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                                <i class="ni ni-world text-lg opacity-10" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
            <div class="card">
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-8">
                            <div class="numbers">
                                <p class="text-sm mb-0 text-capitalize font-weight-bold">Biaya Layanan</p>
                                <h5 class="font-weight-bolder mb-0">
                                    {{"Rp. " .number_format($data['biaya_layanan'])}}
                                </h5>
                            </div>
                        </div>
                        <div class="col-4 text-end">
                            <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                                <i class="ni ni-paper-diploma text-lg opacity-10" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-8">
                            <div class="numbers">
                                <p class="text-sm mb-0 text-capitalize font-weight-bold">Jumlah Peminjam</p>
                                <h5 class="font-weight-bolder mb-0">
                                    {{$data['jumlah_peminjam']. " Pinjaman"}}
                                </h5>
                            </div>
                        </div>
                        <div class="col-4 text-end">
                            <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                                <i class="ni ni-cart text-lg opacity-10" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row my-4">
        <div class="col-lg-12 col-md-6 mb-md-0 mb-4">
            <div class="card">
                <div class="card-header pb-0">
                    <div class="row">
                        <div class="col-lg-6 col-7">
                            <h6>Pinjaman Tertinggi</h6>

                        </div>

                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nama</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Jumlah Pinjaman</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Biaya Layanan</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach($data['data_pinjaman'] as $row)
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">

                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-sm">{{$row->anggota->user->name}}</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="text-xs font-weight-bold"> {{"Rp. " .number_format($row->jumlah_pinjaman)}} </span>
                                    </td>
                                    <td class="align-middle text-center text-sm">
                                        <span class="text-xs font-weight-bold"> {{"Rp. " .number_format($row->biaya_layanan)}}  </span>
                                    </td>
                                </tr>

                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
    @include('templates.footer')
</div>
@endsection

resources/views/admin/form-edit-profile.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0 d-flex justify-content-between align-items-center">
                    <h6>Edit Profile</h6>
                    <a href="{{route('admin.myProfile')}}" class="btn btn-dark btn-sm"><i class="fa fa-arrow-left"></i> Kembali</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <form method="POST" action="{{route('admin.update.profile')}}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="name">Nama</label>
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Nama" value="{{old('name', $admin->name)}}">
                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" value="{{old('email', $admin->email)}}">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="phone">No Telepon</label>
                                    <input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror" placeholder="No Telepon" value="{{old('phone', $admin->phone)}}">
                                    @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="dob">Tanggal Lahir</label>
                                    <input type="date" name="dob" class="form-control @error('dob') is-invalid @enderror" value="{{old('dob', $admin->dob)}}">
                                    @error('dob')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="gender">Jenis Kelamin</label>
                                    <select name="gender" id="gender" class="form-control @error('gender') is-invalid @enderror">
                                        <option value="">Pilih Jenis Kelamin</option>
                                        <option value="L" {{$admin->gender == 'L' ? 'selected' : ''}}>Laki-Laki</option>
                                        <option value="P" {{$admin->gender == 'P' ? 'selected' : ''}}>Perempuan</option>
                                    </select>
                                    @error('gender')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="address">Alamat</label>
                                    <textarea type="text" name="address" class="form-control @error('address') is-invalid @enderror" placeholder="Alamat lengkap">{{old('address', $admin->address)}}</textarea>
                                    @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                @if($admin->avatar !== null)
                                <div class="avatar me-3">
                                    <img src="{{asset($admin->avatar)}}" alt="kal" class="border-radius-lg shadow">
                                </div>
                                @endif

                                <div class="form-group">
                                    <label for="avatar">Foto</label>
                                    <input type="file" name="avatar" class="form-control @error('avatar') is-invalid @enderror">
                                    @error('avatar')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                    <span class="mt-2 text-xs">File berupa : PNG,JPG,JPEG atau GIF maksimal 1MB</span>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection

resources/views/admin/profile.blade.php
@extends('templates.app')

@section('content')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12 col-xl-4">
            <div class="card h-100">
                <div class="card-header pb-0 p-3">
                    <div class="row">
                        <div class="col-md-8 d-flex align-items-center">
                            <h6 class="mb-0">Profil</h6>
                        </div>
                    </div>
                </div>
                <div class="card-body p-3">
                    <hr class="horizontal gray-light my-4">
                    <ul class="list-group">
                        <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Nama:</strong> &nbsp; {{$user->name}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Email:</strong> &nbsp;{{$user->email}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">No Telepon:</strong> &nbsp; {{$user->phone}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Jenis Kelamin:</strong> &nbsp; {{$user->gender}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Tanggal Lahir:</strong> &nbsp; {{$user->dob}}</li>
                        <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Alamat:</strong> &nbsp; {{$user->address}}</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-12 col-xl-4">
            <div class="card h-100">
                <div class="card-header pb-0 p-3 d-flex align-items-center justify-content-between">
                    <h6 class="mb-0">Profil</h6>
                    <a href="{{route('users.edit.profile')}}" class="btn btn-link"><i class="fa fa-edit"></i> Edit</a>
                </div>
                <div class="card-body p-3">
                    <ul class="list-group">
                        <li class="list-group-item border-0 d-flex align-items-center px-0 mb-2">
                            @if($user->avatar == null)
                            <div class="avatar me-3">
                                <img src="{{asset('assets/img/kal-visuals-square.jpg')}}" alt="kal" class="border-radius-lg shadow">
                            </div>
                            @else
                            <div class="avatar me-3">
                                <img src="{{asset('assets/img/avatar/'.$user->avatar)}}" alt="kal" class="border-radius-lg shadow">
                            </div>
                            @endif
                            <div class="d-flex align-items-start flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{$user->name}}</h6>
                                <p class="mb-0 text-xs">{{$user->email}}</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-12 col-xl-4">
            <div class="card card-blog card-plain h-100">
                <div class="position-relative">
                    @if($anggota)
                    @if($anggota->file_ktp)
                    <a class="d-block shadow-xl border-radius-xl">
                        <img src="{{asset('assets/img/ktp/'.$anggota->file_ktp)}}" alt="img-blur-shadow" class="img-fluid shadow border-radius-xl">
                    </a>
                    @else
                    <a class="d-block shadow-xl border-radius-xl">
                        <img src="{{asset('assets/img/curved-images/white-curved.jpg')}}" alt="img-blur-shadow" class="img-fluid shadow border-radius-xl">
                    </a>
                    @endif
                    @endif
                </div>
                <div class="card-body px-1 pb-0">
                    <p class="text-gradient text-dark mb-2 text-sm">KTP FILE</p>
                    <p class="text-gradient text-dark mb-2 text-sm">Nomor KTP</p>
                    <a href="javascript:;">
                        <h5>
                            {{$anggota ? $anggota->nomor_ktp : ''}}
                        </h5>
                    </a>
                    <div class="d-flex align-items-center justify-content-start">
                        <a href="{{route('users.identity.upload')}}" class="btn btn-outline-primary btn-sm mb-0">Edit KTP</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('templates.footer')
</div>
@endsection