routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPinjamanController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\PengajuanPinjamanController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\JenisPinjamanController;
use App\Http\Controllers\Admin\PinjamanController;
use App\Http\Controllers\Admin\PembayaranController;
use App\Http\Controllers\UserPengajuanController;
use App\Http\Controllers\UserPembayaranController;
use App\Http\Controllers\Admin\LaporanController;
use App\Http\Controllers\Admin\PenggunaController;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/profile', [AdminController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [AdminController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [AdminController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [AdminController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [AdminController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', [CustomerController::class, 'index'])->name('index');
            Route::get('/add', [CustomerController::class, 'create'])->name('create');
            Route::post('/add', [CustomerController::class, 'store'])->name('store');
            Route::get('/{user:id}/detail', [CustomerController::class, 'show'])->name('show');
            Route::get('/{user:id}/verif', [CustomerController::class, 'verif'])->name('verif');
            Route::get('/{user:id}', [CustomerController::class, 'edit'])->name('edit');
            Route::get('/{anggota:id}/approved', [CustomerController::class, 'approved'])->name('approved');
            Route::get('/{anggota:id}/reject', [CustomerController::class, 'reject'])->name('reject');
            Route::put('/update/{user:id}', [CustomerController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengguna', 'as' => 'pengguna.'], function () {
            Route::get('/', [PenggunaController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PenggunaController::class, 'show'])->name('show');
            Route::post('/update', [PenggunaController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'jenisPinjaman', 'as' => 'jenisPinjaman.'], function () {
            Route::get('/', [JenisPinjamanController::class, 'index'])->name('index');
            Route::get('/add', [JenisPinjamanController::class, 'create'])->name('create');
            Route::post('/add', [JenisPinjamanController::class, 'store'])->name('store');
            Route::get('/{jenis_pinjaman:id}/detail', [JenisPinjamanController::class, 'show'])->name('show');
            Route::get('/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'edit'])->name('edit');
            Route::put('/update/{jenis_pinjaman:id}', [JenisPinjamanController::class, 'update'])->name('update');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [PengajuanPinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PengajuanPinjamanController::class, 'show'])->name('show');
            Route::get('/approved/{pengajuan:id}', [PengajuanPinjamanController::class, 'approved'])->name('approved');
            Route::get('/reject/{pengajuan:id}', [PengajuanPinjamanController::class, 'reject'])->name('reject');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [PinjamanController::class, 'index'])->name('index');
            Route::get('/show/{id}', [PinjamanController::class, 'show'])->name('show');
            Route::get('/bayar/{id}', [PinjamanController::class, 'bayar'])->name('bayar');
        });

        Route::group(['prefix' => 'laporan', 'as' => 'laporan.'], function () {
            Route::get('/', [LaporanController::class, 'index'])->name('index');
            Route::post('/download', [LaporanController::class, 'download'])->name('download');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [PembayaranController::class, 'index'])->name('index');
            Route::get('/add', [PembayaranController::class, 'add'])->name('add');
            Route::get('/show/{id}', [PembayaranController::class, 'show'])->name('show');
            Route::get('/cetak/{id}', [PembayaranController::class, 'cetak'])->name('cetak');
            Route::post('/bayar', [PembayaranController::class, 'store'])->name('store');
        });
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/profile', [UserController::class, 'myProfile'])->name('myProfile');
        Route::get('/profile-edit', [UserController::class, 'editProfile'])->name('edit.profile');
        Route::put('/update', [UserController::class, 'update'])->name('update.profile');
        Route::get('/change-password', [UserController::class, 'changePassword'])->name('change.password');
        Route::post('/change-password', [UserController::class, 'updatePassword'])->name('update.password');

        Route::group(['prefix' => 'identity', 'as' => 'identity.'], function () {
            Route::get('/upload', [UserController::class, 'uploadIdentity'])->name('upload');
            Route::post('/upload', [UserController::class, 'uploadIdentityStore'])->name('store');
        });

        Route::group(['prefix' => 'pinjaman', 'as' => 'pinjaman.'], function () {
            Route::get('/', [UserPinjamanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPinjamanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPinjamanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pengajuan', 'as' => 'pengajuan.'], function () {
            Route::get('/', [UserPengajuanController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPengajuanController::class, 'detail'])->name('detail');
            Route::get('/ajukan/{jenis_pinjaman:id}', [UserPengajuanController::class, 'ajukan'])->name('ajukan');
        });

        Route::group(['prefix' => 'pembayaran', 'as' => 'pembayaran.'], function () {
            Route::get('/', [UserPembayaranController::class, 'index'])->name('index');
            Route::get('/detail/{id}', [UserPembayaranController::class, 'detail'])->name('detail');
        });
    });
});

resources/views/templates/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="{{asset('assets/img/logo.png')}}">
    <link rel="icon" type="image/png" href="{{asset('assets/img/logo.png')}}">
    <title>{{config('app.name')}} | Admin Management</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link href="{{asset('assets/css/nucleo-icons.css')}}" rel="stylesheet" />
    <link href="{{asset('assets/css/nucleo-svg.css')}}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="{{asset('assets/css/nucleo-svg.css')}}" rel="stylesheet" />
    <link id="pagestyle" href="{{asset('assets/css/soft-ui-dashboard.css?v=1.0.5')}}" rel="stylesheet" />
    {{-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"> --}}
</head>

<body class="g-sidenav-show  bg-gray-100">
    @include('templates.sidebar')
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        @include('templates.navbar')

        <div class="flashdata" data-flashdata="{{ session()->get('success') }}"></div>
        <div class="flasherror" data-flasherror="{{ session()->get('error') }}"></div>
        <div class="container">

        </div>
        @yield('content')

    </main>

    @include('templates.csbutton')

    <script src="{{asset('assets/js/core/popper.min.js')}}"></script>
    <script src="{{asset('assets/js/core/bootstrap.min.js')}}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{{asset('assets/js/plugins/perfect-scrollbar.min.js')}}"></script>
    <script src="{{asset('assets/js/plugins/smooth-scrollbar.min.js')}}"></script>
    <script src="{{asset('assets/js/plugins/chartjs.min.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.8/dist/sweetalert2.all.min.js"></script>

    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <script src="{{asset('assets/js/soft-ui-dashboard.min.js?v=1.0.5')}}"></script>
    <script>
        $('body').on('click', '.btn-delete', function(e) {
            e.preventDefault();
            const href = $(this).attr('href');
            Swal.fire({
                title: 'Apakah anda yakin',
                text: "Data akan dihapus",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus Data!'
            }).then((result) => {
                if (result.value) {
                    window.location.href = href;
                }
            });
        });

        const flashData = $('.flashdata').data('flashdata');
        const flashError = $('.flasherror').data('flasherror');
        if (flashData) {
            Swal.fire('Sukses !', flashData, 'success');
        }
        if (flashError) {
            Swal.fire('Error !', flashError, 'error');
        }
    </script>

    @stack('scripts')
</body>

</html>

resources/views/templates/csbutton.blade.php
<div class="fixed-plugin">
    <a class="fixed-plugin-button bg-success text-dark position-fixed px-3 py-2">
        <i class="fa fa-whatsapp py-2 text-white"></i>
    </a>
</div>

resources/views/templates/footer.blade.php
<footer class="footer pt-3">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-center">
            <div class="col-lg-6 mb-lg-0 mb-4">
                <div class="copyright text-center text-sm text-muted text-lg-start">
                    Copyright © {{date('Y')}} {{config('app.name')}}. Design Creative Tim
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/templates/navbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="/home">Dashboard</a></li>
            </ol>
            <h6 class="font-weight-bolder mb-0">{{config('app.name')}}</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            </div>
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item dropdown pe-2 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-user cursor-pointer"></i>
                    </a>
                    <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                        @if(auth()->user()->role === 'admin' || auth()->user()->role === 'superadmin')
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="{{route('admin.myProfile')}}">
                                <div class="d-flex py-1">
                                    <div class="my-auto avatar avatar-sm bg-gradient-dark me-3">
                                        <i class="fa fa-user cursor-pointer"></i>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">Profil</h6>

                                        <p class="text-xs text-secondary mb-0 ">
                                            <i class="fa fa-check me-1"></i>
                                            {{auth()->user()->name}}
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="{{route('admin.change.password')}}">
                                <div class="d-flex py-1">
                                    <div class="my-auto avatar avatar-sm bg-gradient-dark me-3">
                                        <i class="fa fa-lock cursor-pointer"></i>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">Ubah Password</h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                        @else
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="{{route('users.myProfile')}}">
                                <div class="d-flex py-1">
                                    <div class="my-auto avatar avatar-sm bg-gradient-dark me-3">
                                        <i class="fa fa-user cursor-pointer"></i>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">Profil</h6>

                                        <p class="text-xs text-secondary mb-0 ">
                                            <i class="fa fa-check me-1"></i>
                                            {{auth()->user()->name}}
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="mb-2">
                            <a class="dropdown-item border-radius-md" href="{{route('users.change.password')}}">
                                <div class="d-flex py-1">
                                    <div class="my-auto avatar avatar-sm bg-gradient-dark me-3">
                                        <i class="fa fa-lock cursor-pointer"></i>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">Ubah Password</h6>
                                    </div>
                                </div>
                            </a>
                        </li>
                        @endif

                        <li>
                            <a class="dropdown-item border-radius-md" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <div class="d-flex py-1">
                                    <div class="avatar avatar-sm bg-gradient-secondary me-3 my-auto">
                                        <i class="fa fa-sign-out cursor-pointer"></i>
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="text-sm font-weight-normal mb-1">Logout</h6>
                                    </div>
                                </div>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

resources/views/templates/sidebar.blade.php
 <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3" id="sidenav-main">
     <div class="sidenav-header">
         <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
         <a class="navbar-brand m-0" href="/home">
             <img src="{{asset('assets/img/logo.png')}}" class="navbar-brand-img h-100" alt="main_logo">
             <span class="ms-1 font-weight-bold">{{config('app.name')}}</span>
         </a>
     </div>
     <hr class="horizontal dark mt-0">
     <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
         <ul class="navbar-nav">
             @if(auth()->user()->role === 'superadmin' || auth()->user()->role === 'admin')
             <li class="nav-item">
                 <a class="nav-link {{request()->is('home*') ? 'active' : ''}}" href="{{route('home')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-dashboard {{request()->is('home*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Dashboard</span>
                 </a>
             </li>
             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/pengguna*') ? 'active' : ''}}" href="{{route('admin.pengguna.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-user {{request()->is('admin/pengguna*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pengguna</span>
                 </a>
             </li>
             <li class="nav-item mt-3">
                 <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Manajemen Data</h6>
             </li>
             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/customers*') ? 'active' : ''}}" href="{{route('admin.customers.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-users {{request()->is('admin/customers*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Customers</span>
                 </a>
             </li>



             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/jenisPinjaman*') ? 'active' : ''}}" href="{{route('admin.jenisPinjaman.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-folder {{request()->is('admin/customers*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Jenis Pinjaman</span>
                 </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/pengajuan*') ? 'active' : ''}}" href="{{route('admin.pengajuan.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-folder {{request()->is('admin/customers*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pengajuan Pinjaman</span>
                 </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/pinjaman*') ? 'active' : ''}}" href="{{route('admin.pinjaman.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-folder {{request()->is('admin/customers*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pinjaman</span>
                 </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/pembayaran*') ? 'active' : ''}}" href="{{route('admin.pembayaran.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-folder {{request()->is('admin/customers*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pembayaran</span>
                 </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link {{request()->is('admin/laporan*') ? 'active' : ''}}" href="{{route('admin.laporan.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-folder {{request()->is('admin/laporan*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Laporan</span>
                 </a>
             </li>

             @endif
             @if(auth()->user()->role === 'customer')
             <li class="nav-item mt-3">
                 <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">General</h6>
             </li>
             <li class="nav-item">
                 <a class="nav-link {{request()->is('users/profile*') ? 'active' : ''}}" href="{{route('users.myProfile')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-user {{request()->is('users/profile*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Profil</span>
                 </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link {{request()->is('users/pengajuan*') ? 'active' : ''}}" href="{{route('users.pengajuan.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-book {{request()->is('users/pengajuan*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pengajuan</span>
                 </a>
             </li>
             <li class="nav-item">
                 <a class="nav-link {{request()->is('users/pinjaman*') ? 'active' : ''}}" href="{{route('users.pinjaman.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-book {{request()->is('users/pinjaman*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pinjaman</span>
                 </a>
             </li>

             <li class="nav-item">
                 <a class="nav-link {{request()->is('users/pembayaran*') ? 'active' : ''}}" href="{{route('users.pembayaran.index')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-book {{request()->is('users/pembayaran*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Pembayaran</span>
                 </a>
             </li>





             <li class="nav-item">
                 <a class="nav-link {{request()->is('users/change-password*') ? 'active' : ''}}" href="{{route('users.change.password')}}">
                     <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
                         <i class="fa fa-lock {{request()->is('users/change-password*') ? 'text-white' : 'text-secondary'}} cursor-pointer"></i>
                     </div>
                     <span class="nav-link-text ms-1">Ubah Password</span>
                 </a>
             </li>
             @endif
         </ul>
     </div>
 </aside>

resources/views/templates/simple-footer.blade.php
<footer class="footer py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
                <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
                    <span class="text-lg fab fa-facebook"></span>
                </a>
                <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
                    <span class="text-lg fab fa-twitter"></span>
                </a>
                <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
                    <span class="text-lg fab fa-instagram"></span>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-8 mx-auto text-center mt-1">
                <a href="tel:082275963992" class="mb-0 text-success text-bold d-block">Telp : 0822-7596-3992</a>
                <a href="#" target="_blank" class="mb-0 text-secondary text-bold">KSP RAJAWALI CITRA MANDIRI, Ruko Permata Regency</a>
                </br>
                <a href="mailto:sabarpanjaitan@gmail.com" class="mb-0 text-secondary text-bold">Email : sabarpanjaitan@gmail.com</a>
            </div>
        </div>
        <div class="row">
            <div class="col-8 mx-auto text-center mt-1">
                <p class="mb-0 text-secondary">
                    Copyright © {{date("Y")}} {{config('app.name')}}
                </p>
            </div>
        </div>
    </div>
</footer>